In [1]:
import cv2
import pytesseract

import numpy as np
import os

In [2]:

vidcap = cv2.VideoCapture('task.mp4')
vidcap.set(cv2.CAP_PROP_POS_AVI_RATIO,1)
durationsec=int(vidcap.get(cv2.CAP_PROP_POS_MSEC)/1000)
print("duration: "+str(durationsec)+" sec")


duration: 895 sec


In [11]:
thissec=15

vidcap.set(cv2.CAP_PROP_POS_MSEC,thissec*1000)
success,image = vidcap.read()
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
ret, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)
if thresh[0][0]==0:
    thresh = cv2.bitwise_not(thresh)
print(thresh)
    

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [98]:
U = 0
A = 0
Y = 0
B = 0
G = 0
I = 0
X = 0
T = 0
W = 0
R = 0
O = 0
M = 0
V = 0
D = 0

In [76]:
st = 'Vvop'
if ('V' in st or 'v' in st) and ')' not in st:
    print(st)

Vvop


In [99]:

for thissec in range(10,895,1):
    vidcap.set(cv2.CAP_PROP_POS_MSEC,thissec*1000)
    success,image = vidcap.read()
    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
    ret, thresh = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY_INV+cv2.THRESH_OTSU)
    if thresh[0][0]==0:
        thresh = cv2.bitwise_not(thresh)

    thresh = cv2.addWeighted( thresh, 0, thresh, 0, 0)
    if success:
        print(str(thissec)+" sec.")
        text = pytesseract.image_to_string(image,lang='eng', config='--psm 6', output_type='string' )
        print(text)
        if 'T' in text or '7' in text or '+' in text:
            T += 1
        print("----")

10 sec.
iV
----
11 sec.
Xx
----
12 sec.
U
----
13 sec.
R
----
14 sec.
U
----
15 sec.
R
----
16 sec.
+
----
17 sec.
x
----
18 sec.
U
----
19 sec.
xX
----
20 sec.
R
----
21 sec.
U
----
22 sec.
iV
----
23 sec.
xX
----
24 sec.
U
----
25 sec.
x.
----
26 sec.
D
----
27 sec.
U
----
28 sec.
3)
----
29 sec.
xX
----
30 sec.
U
----
31 sec.
3)
----
32 sec.
I
----
33 sec.
U
----
34 sec.

----
35 sec.
xX
----
36 sec.
T
----
37 sec.
e
----
38 sec.
U
----
39 sec.
B
----
40 sec.
M
----
41 sec.
7
----
42 sec.
G
----
43 sec.
x.
----
44 sec.
M
----
45 sec.
U
----
46 sec.
Vi
----
47 sec.
M
----
48 sec.
U
----
49 sec.
X
----
50 sec.
7
----
51 sec.
x
----
52 sec.
U
----
53 sec.
I
----
54 sec.
U
----
55 sec.
M
----
56 sec.
U
----
57 sec.
¥
----
58 sec.
M
----
59 sec.
U
----
60 sec.
X
----
61 sec.
I
----
62 sec.
e
----
63 sec.
U
----
64 sec.
e
----
65 sec.
U
----
66 sec.
T
----
67 sec.
U
----
68 sec.

----
69 sec.
U
----
70 sec.
iV
----
71 sec.
R
----
72 sec.
U
----
73 sec.
R
----
74 sec.
D
----
75 sec.
M
----

B
----
523 sec.
Y
----
524 sec.
7
----
525 sec.
U
----
526 sec.
7
----
527 sec.
jt
----
528 sec.
M
----
529 sec.
U
----
530 sec.
M
----
531 sec.
U
----
532 sec.
B
----
533 sec.
Xx
----
534 sec.
T
----
535 sec.
U
----
536 sec.
T
----
537 sec.
U
----
538 sec.
B
----
539 sec.
R
----
540 sec.
T
----
541 sec.
U
----
542 sec.
iV
----
543 sec.
M
----
544 sec.
B
----
545 sec.
A
----
546 sec.
O
----
547 sec.
U
----
548 sec.
Vi
----
549 sec.
J
----
550 sec.
M
----
551 sec.
V
----
552 sec.
U
----
553 sec.
B
----
554 sec.
U
----
555 sec.
x.
----
556 sec.
Y
----
557 sec.
it
----
558 sec.
B
----
559 sec.
T
----
560 sec.
Vi
----
561 sec.
T
----
562 sec.
Y
----
563 sec.
T
----
564 sec.
B
----
565 sec.
U
----
566 sec.
M
----
567 sec.
T
----
568 sec.
x
----
569 sec.
U
----
570 sec.
e
----
571 sec.
xX
----
572 sec.
U
----
573 sec.

----
574 sec.
A
----
575 sec.
B
----
576 sec.
A
----
577 sec.
M
----
578 sec.
B
----
579 sec.
Y
----
580 sec.
U
----
581 sec.
xX
----
582 sec.
Y
----
583 sec.
V
----
584 sec.


In [ ]:
'''       if 'V' in text or 'v' in text:
            V += 1
        #elif 'x' in text or 'X' in text:
           # X += 1 
        elif 'U' in text:
            U +=1
        elif 'M' in text:
            M +=1
        elif ('I' in text or 't' in text or 'J' in text) and ')' not in text:
            I +=1
        elif 'e' in text:
            O+=1
        #elif 'A' in text:
        #    A +=1
        elif 'D' in text:
            D += 1
        elif 'G' in text:
            G += 1
        elif 'B' in text or ')' in text:
            B+=1
        elif 'W' in text:
            W +=1 
        elif 'R' in text:
            R +=1
        ''

In [100]:

print(A)
print(B)
print(D)
print(G)
print(I)
print(M)
print(O)
print(U)
print(V)
print(W)
print(X)
print(R)

print(T)








0
0
0
0
0
0
0
0
0
0
0
0
83


In [81]:
print(M)

87


In [43]:
elif 'D' in text:
    D += 1
elif 'G' in text:
    G += 1
elif 'G' in text:


In [37]:
k = []
d = {'nnn': 4}
text = ['abb', 'nnn', 'g', 'l', 'r', 'r','abb', 'p', 'r']

In [39]:
for word in text:
    if word in d.keys():
        d[word] += 1
    else:
        
print(d)

{'nnn': 5}
